{{- /* krateo:placed AwsRdsStack composition.krateo.io/v0-3-0 (composition) — written when it was placed; the rest of this file is yours. */}}
apiVersion: composition.krateo.io/v0-3-0
kind: AwsRdsStack
metadata:
  name: {{ printf "%s-awsrdsstack" $.Release.Name | trunc 63 | trimSuffix "-" }}
  namespace: {{ $.Release.Namespace }}
spec:
  engine: ""
  identifier: ""
  instance_class: ""
  # optional: allocated_storage, auto_minor_version_upgrade, availability_zone, backup_retention_period, backup_window, ca_cert_identifier, copy_tags_to_snapshot, create_db_parameter_group, create_db_subnet_group, db_instance_tags, db_name, db_parameter_group_tags … and 33 more
